# Generated by Django 3.2 on 2021-05-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('selected_cards', models.ManyToManyField(to='core.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_to_win', models.IntegerField(default=10)),
                ('current_round', models.IntegerField(default=0)),
                ('current_player', models.IntegerField(default=0)),
                ('judge', models.IntegerField(default=0)),
                ('players', models.ManyToManyField(to='core.Player')),
            ],
        ),
    ]
