# Generated by Django 3.2 on 2021-05-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_cards',
            field=models.ManyToManyField(to='core.Card'),
        ),
    ]
