# Generated by Django 3.2 on 2021-05-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_current_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='selected_cards',
            new_name='cards_to_select',
        ),
        migrations.AddField(
            model_name='player',
            name='selected_card',
            field=models.IntegerField(default=0),
        ),
    ]
