# Generated by Django 3.2 on 2021-05-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_game_last_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='cards_to_select',
        ),
    ]
