# Generated by Django 3.2 on 2021-05-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_player_cards_to_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_image',
            field=models.IntegerField(default=0),
        ),
    ]
