# Generated by Django 3.2 on 2021-05-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_game_current_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
